# =================================================================
# 1. GRAFANA CONFIGURATION (Datasources, Providers & Dashboard JSON)
# =================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  # ---------------------------------------------------------
  # A. DATASOURCES
  # ---------------------------------------------------------
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: PBFA97CFB590B2093
        url: http://monitor-stack-kube-prometh-prometheus.monitoring:9090
        access: proxy
        isDefault: true
      - name: Postgres
        type: postgres
        url: chatbottesting:5432
        user: eraytaspinar
        database: postgres
        jsonData:
          sslmode: "disable"
        secureJsonData:
          password: "$POSTGRES_PASSWORD"

  # ---------------------------------------------------------
  # B. DASHBOARD PROVIDER
  # ---------------------------------------------------------
  providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /etc/grafana/custom_dashboards

  # ---------------------------------------------------------
  # C. THE DASHBOARD JSON
  # ---------------------------------------------------------
  langchain-dashboard.json: |
    {
      "annotations": { "list": [ { "builtIn": 1, "datasource": { "type": "grafana", "uid": "-- Grafana --" }, "enable": true, "hide": true, "iconColor": "rgba(0, 211, 255, 1)", "name": "Annotations & Alerts", "type": "dashboard" } ] },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 0,
      "links": [],
      "panels": [
        { "collapsed": false, "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "id": 10, "panels": [], "title": "Resource Usage (CPU & Memory)", "type": "row" },
        { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "fieldConfig": { "defaults": { "color": { "mode": "palette-classic" }, "custom": { "axisBorderShow": false, "axisCenteredZero": false, "axisColorMode": "text", "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "barWidthFactor": 0.6, "drawStyle": "line", "fillOpacity": 15, "gradientMode": "opacity", "hideFrom": { "legend": false, "tooltip": false, "viz": false }, "insertNulls": false, "lineInterpolation": "linear", "lineWidth": 1, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "auto", "showValues": false, "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [ { "color": "green", "value": 0 } ] }, "unit": "none" }, "overrides": [] }, "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 }, "id": 1, "options": { "legend": { "calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true }, "tooltip": { "hideZeros": false, "mode": "single", "sort": "none" } }, "pluginVersion": "12.3.0", "targets": [ { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "editorMode": "code", "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"(postgres|langchain|frontend).*\"}[5m])) by (pod)", "legendFormat": "{{pod}}", "range": true, "refId": "A" } ], "title": "CPU Usage (Rate)", "type": "timeseries" },
        { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "fieldConfig": { "defaults": { "color": { "mode": "palette-classic" }, "custom": { "axisBorderShow": false, "axisCenteredZero": false, "axisColorMode": "text", "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "barWidthFactor": 0.6, "drawStyle": "line", "fillOpacity": 15, "gradientMode": "opacity", "hideFrom": { "legend": false, "tooltip": false, "viz": false }, "insertNulls": false, "lineInterpolation": "linear", "lineWidth": 1, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "auto", "showValues": false, "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [ { "color": "green", "value": 0 } ] }, "unit": "bytes" }, "overrides": [] }, "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 }, "id": 2, "options": { "legend": { "calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true }, "tooltip": { "hideZeros": false, "mode": "single", "sort": "none" } }, "pluginVersion": "12.3.0", "targets": [ { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "editorMode": "code", "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"(postgres|langchain|frontend).*\"}) by (pod)", "legendFormat": "{{pod}}", "range": true, "refId": "A" } ], "title": "Memory Usage (RAM)", "type": "timeseries" },
        { "collapsed": false, "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "id": 11, "panels": [], "title": "Traffic & Saturation", "type": "row" },
        { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "fieldConfig": { "defaults": { "color": { "mode": "palette-classic" }, "custom": { "axisBorderShow": false, "axisCenteredZero": false, "axisColorMode": "text", "axisLabel": "", "axisPlacement": "auto", "barAlignment": 0, "barWidthFactor": 0.6, "drawStyle": "line", "fillOpacity": 10, "gradientMode": "none", "hideFrom": { "legend": false, "tooltip": false, "viz": false }, "insertNulls": false, "lineInterpolation": "linear", "lineWidth": 1, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "auto", "showValues": false, "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [ { "color": "green", "value": 0 } ] }, "unit": "binBps" }, "overrides": [] }, "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 }, "id": 3, "options": { "legend": { "calcs": [], "displayMode": "list", "placement": "bottom", "showLegend": true }, "tooltip": { "hideZeros": false, "mode": "single", "sort": "none" } }, "pluginVersion": "12.3.0", "targets": [ { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "editorMode": "code", "expr": "sum(rate(process_network_receive_bytes_total{}[5m]))", "legendFormat": "{{label_name}} Received Bytes Total", "range": true, "refId": "A" } ], "title": "Traffic Load (Network Receive)", "type": "timeseries" },
        { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "description": "If this number goes up, your pods are crashing.", "fieldConfig": { "defaults": { "color": { "mode": "thresholds" }, "custom": { "align": "auto", "cellOptions": { "type": "auto" }, "footer": { "reducers": [] }, "inspect": false }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [ { "color": "green", "value": 0 }, { "color": "red", "value": 1 } ] } }, "overrides": [] }, "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 }, "id": 4, "options": { "cellHeight": "sm", "showHeader": true, "sortBy": [] }, "pluginVersion": "12.3.0", "targets": [ { "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "editorMode": "code", "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"(postgres|langchain|frontend).*\"}[1h])) by (pod)", "legendFormat": "{{pod}}", "range": true, "refId": "A" } ], "title": "Pod Restarts (Last 1hr)", "type": "table" }
      ],
      "preload": false, "refresh": "5s", "schemaVersion": 42, "tags": [],
      "templating": { "list": [ { "current": { "text": "Prometheus", "value": "PBFA97CFB590B2093" }, "includeAll": false, "label": "Datasource", "name": "DS_PROMETHEUS", "options": [], "query": "prometheus", "refresh": 1, "regex": "", "type": "datasource" }, { "current": { "text": "default", "value": "default" }, "datasource": { "type": "prometheus", "uid": "${DS_PROMETHEUS}" }, "definition": "label_values(kube_pod_info, namespace)", "includeAll": false, "label": "Namespace", "name": "namespace", "options": [], "query": { "query": "label_values(kube_pod_info, namespace)", "refId": "StandardVariableQuery" }, "refresh": 1, "regex": "", "type": "query" } ] },
      "time": { "from": "now-1h", "to": "now" }, "timepicker": {}, "timezone": "", "title": "Langchain", "uid": "app-stack-monitor-v1", "version": 3
    }

---
# =================================================================
# 2. GRAFANA DEPLOYMENT
# =================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
          volumeMounts:
            # 1. Mount Datasource Config
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              subPath: datasources.yaml
              readOnly: true
            
            # 2. Mount Provider Config
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/dashboards/providers.yaml
              subPath: providers.yaml
              readOnly: true
            
            # 3. Mount Dashboard JSON
            - name: grafana-config
              mountPath: /etc/grafana/custom_dashboards/langchain-dashboard.json
              subPath: langchain-dashboard.json
              readOnly: true

      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config

---
# =================================================================
# 3. GRAFANA SERVICE
# =================================================================
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana